apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp1
  labels:
    app: dotnet
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dotnet
  template:
    metadata:
      labels:
        app: dotnet
    spec:
      containers:
      - name: webapp
        image: pepsi16/web1
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
        env:
        - name: IsProduction
          value: "false"

---
apiVersion: v1
kind: Service
metadata:
  name: webapp1
spec:
  type: NodePort
  selector:
    app: dotnet  
  ports:
  - name: webdotnet
    protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 31234


# deployment:
#   name: webapp1-dev
#   appLabel: dotnet-dev
#   container:
#     name: webapp
#     env:
#       IsProduction: "false"