name: DockerBuildPush

on:
  push:
    branches: [main]

jobs:
    docker:
       runs-on: ubuntu-latest
       steps:
         -
          name: Checkout
          uses: actions/checkout@v4
         -
          name: Login to Docker Hub
          uses: docker/login-action@v3
          with:
            username: ${{variables.USERNAME_DOCKER}}
            password: ${{secrets.PASSWORD}}
         -
            name: Build and push
            uses: docker/build-push-action@v6
            with:
              push: true
              tags: pepsi/webci:latest


